### ISSUE TITLE
ONIE Partition Size Hardcoded

### ISSUE THREAD

**Issue by gerritavenant** [NetworkGradeLinux/meta-mion#66] opened 2021-01-08 13:28 UTC
https://github.com/NetworkGradeLinux/meta-mion/blob/5dca40266a5f887b3e25561778782a0d68986156/meta-mion/recipes-onie/images/files/grub-env/install.sh#L17

Hi, the partition size is hardcoded to 4GB. I could easily resize this via `parted` and `resizefs` post install, but would be great if this could be preset to reduce post installation steps. (BF SDE binaries is already pushing it past the 4GB limit).  
Possibly an environment variable contained in each switches configuration file, or in the build-script, with 4GB as default if nothing specified?

**Comment by johntoomey** [comment] 2021-01-12 10:47
This needs to be fixed for the next release. It is the default behavior in the example code provided by ONIE to hardcode a size in the install script but this clearly isnt going to work for us. The plan is to use the full space available on the disk by default unless the the user specifically provides a size variable in the BSP for the machine.

**Comment by johntoomey** [comment] 2021-01-12 11:20
@frederic-loui

**Comment by N-Mc-Nally** [comment] 2021-01-14 11:17
As per engineering stand-up 14/01/21 - @johntoomey has a solution and can get to it early next week.

**Comment by johntoomey** [comment] 2021-01-15 11:47
this is a duplicate of https://github.com/NetworkGradeLinux/meta-mion/issues/58

**Closed as completed by johntoomey** 2021-01-15 11:47 UTC
Labels: duplicate
